// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCuaznsZNryYEETu4_tPrmXfXRlzYc4G-E',
    appId: '1:686440382313:web:7876d3cd1b4265e2efc7f8',
    messagingSenderId: '686440382313',
    projectId: 'melendar-c726f',
    authDomain: 'melendar-c726f.firebaseapp.com',
    storageBucket: 'melendar-c726f.firebasestorage.app',
    measurementId: 'G-GF66DXTJVK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAsI0hC2_kS3HsZ_M5O10u1rEoSUS1jg-4',
    appId: '1:686440382313:android:20ad730297617efbefc7f8',
    messagingSenderId: '686440382313',
    projectId: 'melendar-c726f',
    storageBucket: 'melendar-c726f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDojFZegh_VmBLmXxX4g6gzgp486nDff2c',
    appId: '1:686440382313:ios:926bab506bc90bd7efc7f8',
    messagingSenderId: '686440382313',
    projectId: 'melendar-c726f',
    storageBucket: 'melendar-c726f.firebasestorage.app',
    iosBundleId: 'com.example.melendarBack',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDojFZegh_VmBLmXxX4g6gzgp486nDff2c',
    appId: '1:686440382313:ios:926bab506bc90bd7efc7f8',
    messagingSenderId: '686440382313',
    projectId: 'melendar-c726f',
    storageBucket: 'melendar-c726f.firebasestorage.app',
    iosBundleId: 'com.example.melendarBack',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCuaznsZNryYEETu4_tPrmXfXRlzYc4G-E',
    appId: '1:686440382313:web:0f5a3809a7eeed03efc7f8',
    messagingSenderId: '686440382313',
    projectId: 'melendar-c726f',
    authDomain: 'melendar-c726f.firebaseapp.com',
    storageBucket: 'melendar-c726f.firebasestorage.app',
    measurementId: 'G-YJ164GSRVH',
  );
}
